### PR TITLE
Various fixes

### LINKED ISSUE #1: Missing <stdexcept>
`generator.hpp` needs to include `<stdexcept>`, otherwise I get errors about `std::out_of_range` being undeclared.

### PR DESCRIPTION
**Pull request by mrzv**
Fixes #1 and #2.

### CODE REVIEW

**Comment by LEW21** [comment]
I think the change in generator.hpp will break when somebody moves the generator object - as lambda's this pointer won't change.

The rest of the changes are OK, thanks!

I don't have #2's error when I compile the project with gcc 4.9.2 in C++14 mode, what compiler do you use?

**Comment by mrzv** [comment]
I'm using clang++ (3.6, I believe), but in C++11 mode. The README says that it's supposed to work in C++11 mode, and #2 is the only line that forces C++14 mode.

I did test the changes with the move semantics (it's the second to last test in your `test.cpp`). What I did originally indeed broke the move, but not what I actually submitted as the pull request. Your test passes with these changes. I don't completely understand why it works; maybe because `this` has a special meaning in the capture list and does not just blindly capture the pointer? I'm not 100% certain, but, like I said, your test passes.

**Comment by mrzv** [comment]
Actually, digging around a little more, I'm not sure how `this` interacts with the move semantics, but that line never gets executed past the first call to `coro()`, which happens in that very same constructor. So `this` cannot change between initialization and that first call. Subsequent calls to `coro()` re-enter the generator context, where the previous `yield()` left off. In other words, I think it's safe.

**Comment by LEW21** [comment]
I merged the changes in generator.hpp, and I've decided against fixing C++11 support.

**Pull request closed without merging**
